version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ktor_postgres
    restart: always
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: pgsql
      POSTGRES_DB: kmpquizdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: